name-template: Gerbera v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION

autolabeler:
  - label: 'bug'
    branch:
      - '/fix/i'
    title:
      - '/fix/i'
  - label: 'update'
    branch:
      - '/update/i'
      - '/bump/i'
    title:
      - '/update/i'
      - '/bump/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'

categories:
  - title: '🌼 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐞 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📚 Dependencies'
    labels:
      - 'update'
      - 'library'
      - 'dependencies'

exclude-labels:
  - ignore
  - release
change-template: ' * $TITLE (#$NUMBER), thanks @$AUTHOR'
no-changes-template: ' * Nothing'

template: |
  We are happy to announce that Gerbera Media Server $NEXT_PATCH_VERSION is now available.

  ## Changes

  $CHANGES

  ## Documentation

  Please see our [Documentation](https://docs.gerbera.io/en/stable) for how to [install the latest stable Gerbera version](https://docs.gerbera.io/en/stable/install.html) on your system.
  
  ## Full Changelog
  https://github.com/gerbera/gerbera/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
