name-template: Gerbera v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
exclude-labels:
  - ignore
  - release
change-template: ' * $TITLE (#$NUMBER), thanks @$AUTHOR'
no-changes-template: ' * Nothing'
template: |
  We are happy to announce that Gerbera Media Server $NEXT_PATCH_VERSION is now available.

  ## Changes

  $CHANGES

  Please see our [Documentation](https://docs.gerbera.io/en/stable) for how to [install the latest Gerbera version](https://docs.gerbera.io/en/stable/install.html) on your system.
  
