#!/bin/sh
#
# mediatomb This script starts and stops the mediatomb daemon
#
# chkconfig: - 95 30
# processname: mediatomb
# description: mediatomb is a daemon process which provides a UPnP service

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

# Set default mediatomb configuration.
INTERFACE="eth1"
# make sure to run it as nobody
MEDIATOMB="-d -u nobody -g nobody"

# either make an installation in /etc/mediatomb and leave this blank,
# or specify an alternative config file location using the -c option
# Note: be aware, that -i parameter is used to set the ip of the 
# interface specified above
MEDIATOMBOPTIONS=""


[ -f /usr/bin/mediatomb ] || exit 0
PATH=$PATH:/usr/bin:/usr/local/bin

IFACE_IP=`ifconfig | grep -i "$INTERFACE" -A 1|grep "inet addr"|cut -d " " -f 12|cut -d ":" -f 2`

# By default it's all good
RETVAL=0

# See how we were called.
case "$1" in
  start)
	# Start daemon.
	echo -n "Starting mediatomb: "
    # those settings are necessary for us to react to M-SEARCH requests
    route add -net 239.0.0.0 netmask 255.0.0.0 $SETMULTICAST >/dev/null 2>&1
    ifconfig $SETMULTICAST allmulti
	daemon $NICELEVEL mediatomb $MEDIATOMB -i $IFACE_IP $MEDIATOMBOPTIONaS
	RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch /var/lock/subsys/mediatomb
        ;;
  stop)
        # Stop daemons.
        echo -n "Shutting down mediatomb: "
        killproc mediatomb
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f /var/lock/subsys/mediatomb
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  condrestart)
       [ -e /var/lock/subsys/mediatomb ] && $0 restart
       ;;
  status)
	status mediatomb
	RETVAL=$?
	;;
  *)
	echo "Usage: $0 {start|stop|restart|status|condrestart}"
	RETVAL=1
	;;
esac

exit $RETVAL
