#!/bin/sh
. /home/gerbera/gerbera.conf
# -d option dropped from mediatomb -> gerbera; output will go to
#  /var/svc/log/application-gerbera:default.log
# launch with &, otherwise instead of "start" exited with status 0
#       will get Method or service exit timed out. Killing contract xxxx.
# leave stderr to go to the log; 
# below would also send stderr to oblivion
# & > /dev/null 2>&1
/usr/local/bin/gerbera \
    -l $MT_LOGFILE \
    -m $MT_HOME \
    -f $MT_CFGDIR \
    -p $MT_PORT \
    --interface $MT_INTERFACE \
    $MT_OPTIONS \
    & > /dev/null
