FIND_PATH(LIBMAGIC_INCLUDE_DIR magic.h)

FIND_LIBRARY(LIBMAGIC_LIBRARIES NAMES magic)

# handle the QUIETLY and REQUIRED arguments and set LIBMAGIC_FOUND to TRUE
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBMAGIC DEFAULT_MSG LIBMAGIC_INCLUDE_DIR)

MARK_AS_ADVANCED( LIBMAGIC_LIBRARIES LIBMAGIC_INCLUDE_DIRS )