set(CPACK_PACKAGE_VENDOR Gerbera)
set(CPACK_PACKAGE_NAME gerbera)
set(CPACK_PACKAGE_CONTACT "Team Gerbera")
set(CPACK_PACKAGE_VERSION ${GERBERA_VERSION})
set(CPACK_STRIP_FILES YES)

# Debian Specifics
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_SECTION "net")
set(CPACK_DEBIAN_COMPRESSION_TYPE "xz")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON) # Discover Deps
set(CPACK_DEBIAN_PACKAGE_DEBUG ON)
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/scripts/debian/postinst")
set(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION ON)

include(CPack)
